2025-01-29 00:15:37.902 [warning] Via 'product.json#extensionEnabledApiProposals' extension 'ms-vscode.vscode-selfhost-test-provider' wants API proposal 'attributableCoverage' but that proposal DOES NOT EXIST. Likely, the proposal has been finalized (check 'vscode.d.ts') or was abandoned.
2025-01-29 00:15:37.902 [warning] Via 'product.json#extensionEnabledApiProposals' extension 'ms-python.python' wants API proposal 'contribIssueReporter' but that proposal DOES NOT EXIST. Likely, the proposal has been finalized (check 'vscode.d.ts') or was abandoned.
2025-01-29 00:15:37.903 [warning] Via 'product.json#extensionEnabledApiProposals' extension 'ms-python.debugpy' wants API proposal 'contribIssueReporter' but that proposal DOES NOT EXIST. Likely, the proposal has been finalized (check 'vscode.d.ts') or was abandoned.
2025-01-29 00:15:38.720 [info] Started local extension host with pid 78059.
2025-01-29 00:15:40.475 [info] Settings Sync: Token updated for the account zefixed
2025-01-29 00:15:40.626 [info] Settings Sync: Account status changed from uninitialized to available
2025-01-29 00:15:41.640 [info] [perf] Render performance baseline is 137ms
2025-01-29 00:15:44.196 [error] [Extension Host] (node:78059) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(Use `exe --trace-deprecation ...` to show where the warning was created)
2025-01-29 00:15:45.098 [warning] Authentication provider codeium_auth was not declared in the Extension Manifest.
2025-01-29 00:17:08.513 [error] [text file model] handleSaveError(20) - exit - resulted in a save error: Error: Unable to write file '/home/zefixed/Documents/python/lzparser/lzparser.py' (NoPermissions (FileSystemError): Error: EACCES: permission denied, open '/home/zefixed/Documents/python/lzparser/lzparser.py') file:///home/zefixed/Documents/python/lzparser/lzparser.py
2025-01-29 00:17:12.141 [error] [text file model] handleSaveError(20) - exit - resulted in a save error: Error: Unable to write file '/home/zefixed/Documents/python/lzparser/lzparser.py' (NoPermissions (FileSystemError): Error: EACCES: permission denied, open '/home/zefixed/Documents/python/lzparser/lzparser.py') file:///home/zefixed/Documents/python/lzparser/lzparser.py
2025-01-29 00:17:12.347 [error] [text file model] handleSaveError(20) - exit - resulted in a save error: Error: Unable to write file '/home/zefixed/Documents/python/lzparser/lzparser.py' (NoPermissions (FileSystemError): Error: EACCES: permission denied, open '/home/zefixed/Documents/python/lzparser/lzparser.py') file:///home/zefixed/Documents/python/lzparser/lzparser.py
2025-01-29 00:17:13.000 [error] [text file model] handleSaveError(20) - exit - resulted in a save error: Error: Unable to write file '/home/zefixed/Documents/python/lzparser/lzparser.py' (NoPermissions (FileSystemError): Error: EACCES: permission denied, open '/home/zefixed/Documents/python/lzparser/lzparser.py') file:///home/zefixed/Documents/python/lzparser/lzparser.py
2025-01-29 00:17:14.350 [error] [text file model] handleSaveError(20) - exit - resulted in a save error: Error: Unable to write file '/home/zefixed/Documents/python/lzparser/lzparser.py' (NoPermissions (FileSystemError): Error: EACCES: permission denied, open '/home/zefixed/Documents/python/lzparser/lzparser.py') file:///home/zefixed/Documents/python/lzparser/lzparser.py
2025-01-29 00:17:17.647 [error] [text file model] handleSaveError(20) - exit - resulted in a save error: Error: No polkit authentication agent found. file:///home/zefixed/Documents/python/lzparser/lzparser.py
2025-01-29 00:17:23.052 [error] [text file model] handleSaveError(20) - exit - resulted in a save error: Error: No polkit authentication agent found. file:///home/zefixed/Documents/python/lzparser/lzparser.py
